### ISSUE TITLE
Implement notification/history page

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#12]
# Type definitions

- [x] Create new common SynchronizationResults type:

<details><summary>Original idea</summary>

```
   - SynchronizationResult: Array
   - Timestamp 
   - User
   - Status (READY, IN PROGRESS, FAILURE AND DONE)
   - metadata: {
            metadataType1: ["myId1"],
            metadataType2: ["myId2"],
        }
```

</details>

<details><summary>Implementation</summary>

```ts
export interface SynchronizationResults {
    results: SynchronizationResult[];
    timestamp: Date;
    user: string;
    status: "READY" | "RUNNING" | "FAILURE" | "DONE";
    metadata: MetadataPackage;
}

export interface MetadataPackage {
    [metadataType: string]: any[];
}
```

</details>

- [x] Update existing SynchronizationResult type:

<details><summary>Original idea</summary>

```
   - instance: {id: string; name: string; url: string; **user**: string };
   - status: string; (PENDING, OK, WARNING, ERROR, NETWORK ERROR)
   - importParams: MetadataImportParams;
   - typeReports: any[];
   - stats: {created: number; deleted: number; ignored: number; total: number; updated: number;};
   - report: { typeStats: any[]; messages: any[]; };
```

</details>

<details><summary>Implementation</summary>

```ts
export interface SynchronizationResult extends MetadataImportResponse {
    instance: {
        id: string;
        name: string;
        url: string;
    };
    report: {
        typeStats: MetadataImportStats[];
        messages: any[];
    };
}

export interface MetadataImportResponse {
    status: "PENDING" | "OK" | "WARNING" | "ERROR" | "NETWORK ERROR";
    importParams: MetadataImportParams;
    typeReports: any[];
    stats: MetadataImportStats;
}

export interface MetadataImportStats {
    created: number;
    deleted: number;
    ignored: number;
    updated: number;
    total: number;
}
```
</details>

# Workflow

- [x] 1) Insert SynchronizationResultSet 'in progress' and SynchronizationResult with instance and status 'pending'.

- [x] 2) When each sync process finished we update SynchronizationResult to DHIS2 response status and update the rest of the fields.

- [x] 3) When all sync processes are done we update the status of the SynchronizationResultSet.

# GUI (Object Table)

   - Filter: Text Search Filter, Date Filter and Status Filter
   - Columns: User, Timestamp, Status
   - Contextual action:
      - Details: User, Timestamp, Status, Metadata (Types and Ids), URL to Metadata end point?
      - View Summary: Reuse sync summary and display in a modal.
      - Delete: Delete it from data store

**Comment by SferaDev** [comment]
export interface MetadataImportResponse {
    status: string;
    importParams: MetadataImportParams;
    typeReports: any[];
    stats: {
        created: number;
        deleted: number;
        ignored: number;
        total: number;
        updated: number;
    };
}

export interface SynchronizationResult extends MetadataImportResponse {
    instance: {
        id: string;
        name: string;
        url: string;
    };
    report: {
        typeStats: any[];
        messages: any[];
    };
}
