### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#13]
- [x] [Documentation for the user guide](https://docs.google.com/document/d/1jUIwQWtpwOh-I7SL1rPmGTtTj8M4Ipidw6DQvx7NnXE/edit)

- [x] [Documentation for the developer guide](https://docs.google.com/document/d/1KlpZgLeQTErK6hwMJ7DuYMI-hG1Bd5pZyrXWhxQZEvE/edit)

- [x] [Documentation for the user guide [Phase 2 draft]](https://docs.google.com/document/d/1_Kb_QUQ_-JDTfsbgMwxefV9r0B56FoXfg4Xv1EwVLZg/)

- [x] [Documentation for the developer guide [Phase 2 draft]](https://docs.google.com/document/d/1wICV2usXxmClTcSvfKkSPnWwSZfwzRX6zOGvnMzoHGw)

**Comment by adrianq** [comment]
@SferaDev User Guide looks really good. I will share with the client. I have cleaned up the developer guide and keep just the relevant sections. Can you please fill/change these sections? It shouldn't take you that long as I have removed a few sections. Note there are some old texts from the vaccination app

**Comment by SferaDev** [comment]
> @SferaDev User Guide looks really good. I will share with the client. I have cleaned up the developer guide and keep just the relevant sections. Can you please fill/change these sections? It shouldn't take you that long as I have removed a few sections. Note there are some old texts from the vaccination app

Updated the developer guide for metadata sync

**Comment by adrianq** [comment]
All good here! Already shared with the client both docs. Many thanks @SferaDev !

**Comment by SferaDev** [comment]
Created a copy of User Guide with the changes introduced on Phase 2.

https://docs.google.com/document/d/1_Kb_QUQ_-JDTfsbgMwxefV9r0B56FoXfg4Xv1EwVLZg

- Updated the whole synchronization rule part

- Added brief description of the script

- Updated screenshots of Synchronization History to reflect Sync Rules changes
