### ISSUE TITLE
New permissions configure vs execute

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#147]
The app must be able to distinguish between user roles:
- [ ] Configurators -> WIDP IT team members. They will be able to configure instances and have full access to the app
- [ ] Executors -> WIDP admins. They will only see Sync rules and will be able to execute them against the pre-configured instances (METADATA_SYNC_EXECUTOR)

**Comment by adrianq** [comment]
At the moment, only the executor role is missing
