### ISSUE TITLE
Implement sync rules

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#15]
Once a Metadata object sync has been defined between the master and slave it should be stored in the data store and the application should be able to pull up this record through a search so that it is not required to redefine the sync configuration for future edits. There could be an option to sync once off or store the sync rule.

**Comment by adrianq** [comment]
We would like to store the sync rule e.g. if Facility A has been Synced with Database 1 then store this in a mapping table so that any future changes does not need to be manually mapped again but will sync when a change was made for Facility A. The sync may be initiated manually but you dont want to do the matching manually again.

**Comment by adrianq** [comment]
- [ ] Add icon in every page to load a sync rule
- [ ] Add icon in every page to save a sync rule
- [ ] When clicking on icon we should display a new dialog with the list of sync rules (Object table + Details)
- [ ] Implement sync execution
- [ ] Evaluate if we can somehow show the information in the tables

**Comment by SferaDev** [comment]
# First mock-up proposal

![Sync Rules Step 1](https://user-images.githubusercontent.com/2181866/55648637-24e8b780-57e1-11e9-8d95-6108156edf40.jpg)
![Sync Rules Step 2](https://user-images.githubusercontent.com/2181866/55648638-25814e00-57e1-11e9-88e2-6a4c45345895.jpg)
![Sync Rules Step 3](https://user-images.githubusercontent.com/2181866/55648639-25814e00-57e1-11e9-81bb-c66a1bd74c8d.jpg)
![Sync Rules Step 4](https://user-images.githubusercontent.com/2181866/55648640-25814e00-57e1-11e9-9f88-cb3799c3039f.jpg)
![Sync Rules Step 5](https://user-images.githubusercontent.com/2181866/55648641-25814e00-57e1-11e9-9da2-ed0b0c1645f4.jpg)
![Sync Rules Step 6](https://user-images.githubusercontent.com/2181866/55648642-2619e480-57e1-11e9-8eb0-76582801802a.jpg)
![Sync Rules Step 7](https://user-images.githubusercontent.com/2181866/55648643-2619e480-57e1-11e9-9ba7-f390384e759f.jpg)
![Sync Rules Step 8](https://user-images.githubusercontent.com/2181866/55648636-24e8b780-57e1-11e9-9816-6aa8b7f2fc59.jpg)

**Comment by adrianq** [comment]
-> Sync Rules Landing Page
- [ ] Object table with columns: Name, Description, Origin and Destination
- [ ] Contextual actions: Delete, Edit, Details and Execute

-> Creation wizard
- [ ] General Info
- [ ] Metadata
   - [ ] Dropdown to select the metadata type
   - [ ] Based on that selection we display a different object table (org unit, de, ind, validation rules). The object table doesn't contain any button.
- [ ] Instances Selection
- [ ] Save and Summary

**Comment by SferaDev** [comment]
- Increase pagination to 20

- Add checkbox for selected elements

- Add snackbar to provide feedback

- Add search by name and filter by destination instance
