### ISSUE TITLE
Export to github repo

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#152]
Third action in the app: send to github repo. The idea would be to send the json file to a github repo/branch so it can automatically work as the source of authorized packages, and tracking the metadata changes during the time. This would fill-in the gap that using the metadata sync to send the metadata between instance would be now creating (as before, we were creating packages that we were storing in a github repository)

**Comment by adrianq** [comment]
Done in 2.0.0
