### ISSUE TITLE
Implement support for aggregated in time

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#163]

**Comment by SferaDev** [comment]
@adrianq I've began investigating the aggregation through the ``/analytics`` endpoint. I have some good news and bad news about it.

#### Endpoint formatting

The endpoint has a format variant ``/analytics/dataValueSet.json`` that provides an importable payload for the ``/dataValueSets`` endpoint. This will allow us to directly import the data already aggregated. Also the output is more user-friendly than the table-oriented normal output we were used to.

![image](https://user-images.githubusercontent.com/2181866/76303041-55728480-62c1-11ea-9869-a4dec19bdd12.png)

#### Aggregation in time and the UI

The aggregation in time does not work as we expected and we will need some changes in how we allow the user to select the periods to aggregate the data.

We originally thought that we could tell the analytics endpoint to aggregated in "YEARLY"/"MONTLY"/whatever but there's no such option. If you provide a fixed date range it will always group by year (and there's no option to modify that behavior), also providing a fixed date range does not work with the ``/analytics/dataValueSet.json`` output format.

The alternative is to send the explicit periods (either fixed or relative) that you want to aggregate to: 2019, 201912, 2019Q1, LAST_YEAR, LAST_FIVE_YEARS, etc... This however would be impossible with the dropdown we originally discussed.

I, as a user, would expect something like what the new "Data Visualizer" does:

![image](https://user-images.githubusercontent.com/2181866/76303606-493af700-62c2-11ea-927f-4089267c1547.png)
![image](https://user-images.githubusercontent.com/2181866/76303621-51933200-62c2-11ea-80f3-c21e8412216d.png)
![image](https://user-images.githubusercontent.com/2181866/76303647-5b1c9a00-62c2-11ea-8944-54b30e662d4a.png)

#### Error 414 and URI too long

During my tests with the "Data Visualizer" app, I found out that they do not control the 414 errors either, so if we add too many dimensions we would face the same issue as always (not being able to execute the query).

I would personally add a check in the Wizard step and disallow the user to add more than N dimensions (dataElements/periods/orgUnits) if the resulting API call would be too big to be executed.
