### ISSUE TITLE
Add metadata type filter in metadata sync app for deleted objects

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#172]
Stopped until client agrees to move on from more pressing tasks

**Comment by SferaDev** [comment]
This is not as easy as it seems. Do we really want a Dropdown with (potentially) 70+ metadata types? Which ones do we really want to add to the filter?

Right now they can search by the metadata type on the search box and that would work.

Waiting for feedback from @ifoche about this.

**Comment by adrianq** [comment]
Obsolete. Delete section is not used by any client and we will eventually have to review it
