### ISSUE TITLE
Refine SharingSettings component before moving to d2-ui-components

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#176]
The component was abstracted from @dhis2/d2-ui once we have some more time we should refine the component and apply the following comments.

![image](https://user-images.githubusercontent.com/2181866/66814230-8d55e580-ef36-11e9-8154-35db40a9ed2c.png)
![image](https://user-images.githubusercontent.com/2181866/66814244-93e45d00-ef36-11e9-9330-6be58fbc37d4.png)
![image](https://user-images.githubusercontent.com/2181866/66814263-9b0b6b00-ef36-11e9-912b-4b7ffa7ab669.png)

**Comment by adrianq** [comment]
Something else... align everything to the left and reduce margins in general. Basically, try to mimic current Sharing Setting look&feel. Otherwise, the available space is too small

**Comment by SferaDev** [comment]
> Something else... align everything to the left and reduce margins in general. Basically, try to mimic current Sharing Setting look&feel. Otherwise, the available space is too small

I believe the problem is on ConfirmationDialog in d2-ui-components, we will take care of it.

**Comment by adrianq** [comment]
@SferaDev @tokland We can close this card, right?  or is there anything that still makes sense?

**Comment by SferaDev** [comment]
Yeah it's already implemented
