### ISSUE TITLE
Extend org-unit step

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#234]
Ideas:

- [ ] OrgUnit children toggle (we can include a whole subtrees). Example: DataSets that report in subnational level and you want to include all of them as part of the synchronization without selecting each reportable OU.
- [ ] Multiselect in orgUnit tree. We can query the API once with multiple organisation units
- [ ] Include all orgUnits in an orgUnitGroup (the API allows to filter the dataValues of a given orgUnitGroup).
- [ ] Sync by CODE. Since the ogUnit trees at WHO are sometimes developed in DHIS2 instances with WIP orgUnit trees they might not match the UID. We can also import with CODE and/or orgUnit attribute.

**Comment by adrianq** [comment]
Obsolete
