### ISSUE TITLE
Add 'no mapping' state

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#344]
Include 'no mapping' state to the mapping elements. By default, all objects are automatically mapped to the same uid as now. However, we should include a new contextual action 'Clear Mapping' that delete even the automatic mapping. We will end up with two contextual actions: 'Reset to default values' (that will perform the current behaviour we have in clear mapping) and 'Clear mapping' that will set the object to no mapped.  No mapped objects will no be synced even if they are part of a sync rule. No mapped objects should be stored in the data store (probably something like what we have for excluded objects). We will not store automatic mapping as we currently do (no changes here).
- [x] Implement no mapping state and store in data store.
- [x] Exclude no mapped object from sync process
- [ ] Add contextual actions: 'Reset to default values' and 'Clear Mapping'
- [ ] Add two new buttons on top right corner 'Reset to default values' and 'Clear Mapping'. These buttons will execute this action on all available elements in the table. A confirmation dialog will be displayed before performing the action

**Comment by SferaDev** [comment]
@adrianq Moving last bullet point to #345 as it's related to it
