### ISSUE TITLE
Create button blocks contextual options on small objectTables

### ISSUE THREAD

**Issue by matiasgarcia91** [EyeSeeTea/metadata-synchronization#35]
When the objectTable has few entries and scroll is disabled the Create button overlays on top of the contextual options of the row making it impossible to access them.

![image](https://user-images.githubusercontent.com/15323369/54754023-d1704a00-4be2-11e9-999c-32e057e6bcdb.png)

**Comment by SferaDev** [comment]
Moved to https://github.com/EyeSeeTea/d2-ui-components/issues/40
