### ISSUE TITLE
Validate Instance URL is baseUrl

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#36]
1) Maybe in the Test Connection we should add an error option that detects if the user has not inputed the root of an instance ie: "http://dev2.../api/dataSets" it will likely return a 404 if the user is properly logged in.

2) We could add a validator that before saving checks if the URL includes "/api" through regex.

3) We could even try to strip anything after "/api" on the URL automatically before saving the model.

**Comment by adrianq** [comment]
Discussed this with @SferaDev  and the conclusion is: add extra validation to verify we don't have '/api' anywhere in the url. This validation should be added where we are currently cheking the url contains a http or https (GeneralInfoForm.jsx)
