### ISSUE TITLE
Check that executors cannot delete history records

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#425]

**Comment by idelcano** [comment]
I cannot delete any history record with "METADATA SYNC EXECUTOR" role.

Note: I had to create a role with permissions to use the app "MetaData Synchronization app" and add it to the user created from 0 to test METADATA SYNC EXECUTOR role to use the app.

Maybe metadata roles could include the "M_MetaData_Synchronization" authority
