### ISSUE TITLE
Implement migration mechanism

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#427]
We have changed the dataStore for mapping (program -> eventPrograms)
Add, Remove, Update: 1 -> 2 migration1-2, 2 -> 3 migration2-3.

Support browser closing in middle: config -> version, state, backup

- [x] Model infrastructure 
- [x] React component
- [x] Axios retry
- [x] Document (README / PR)

Later:

- [ ] Currently, a saveDataStore does a PUT, then a POST. In a backup we would want POST/PUT behaviour. Add option to d2-api.dataValues.save.
- [ ] Cypress test (TBD)
- [ ] Model test
- [ ] On error, add button [copy] (internal in div) -> if makes sense, move to d2-ui-components

**Comment by SferaDev** [comment]
Attaching some files of MAL instance before any migration to build cypress tests in the future.

[instances-v0.txt](https://github.com/EyeSeeTea/metadata-synchronization/files/4392457/instances-v0.txt)
[syncRules-v0.txt](https://github.com/EyeSeeTea/metadata-synchronization/files/4392460/syncRules-v0.txt)
[notifications-v0.txt](https://github.com/EyeSeeTea/metadata-synchronization/files/4392461/notifications-v0.txt)

**Comment by adrianq** [comment]
Not relevant anymore. Migration mechanism seems to be enough for now
