### ISSUE TITLE
Bug excluding rules where returned reference field name by API is not equal to model name

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/metadata-synchronization#458]

**Comment by SferaDev** [comment]
I'm not sure if it helps but check out the following method. We use it to handle "children", "attributeValues" and other properties that do not match a collection name. 

https://github.com/EyeSeeTea/metadata-synchronization/blob/development/src/utils/d2.ts#L48

**Comment by xurxodev** [comment]
Yes!! I found the bugs updating this method for include rules of the program because we have not actions  to reverse clean exclude rules.
