### ISSUE TITLE
Implement aggregation for cat option

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#459]

**Comment by SferaDev** [comment]
Investigated the API to introduce this change and it's not possible without doing the aggregation on the application (which we are trying to avoid in all the process).

The API allows to either aggregate all category option dimensions (leading to a single data value per DE/OU/PE) or aggregate per each category option dimension (leading to one data value per DE/OU/PE/COC).

However what we want in this ticket is to aggregate for N category options dimensions while not aggregating for the rest of them. Example (with malaria age CC): 

- 1 Data value per DE/OU/PE for 0-4 years and 5-14 years
- 1 Data value per DE/OU/PR for 14+ years

The API does not allow directly output the first data value with the results of 0-4 years and 5-14 years together.

The Pivot Tables app also does not support this, when selecting N categories from the sidebar you still see them as separate values and not aggregated.

**Comment by adrianq** [comment]
We can discuss now by meet but I think this is what we want, right_
![image](https://user-images.githubusercontent.com/6850223/78005854-1372b680-7334-11ea-81cb-8c1278424059.png)
http://dev2.eyeseetea.com:8085/api/29/analytics?dimension=dx:dFaBg0HpoIL&dimension=pe:LAST_5_YEARS&filter=ou:E4h5WBOg71F&filter=mFoasCYViMW:UPvKbcqTEY3;pa0cY66MrG6&displayProperty=NAME&skipMeta=true&includeNumDen=true
