### ISSUE TITLE
Set up demo servers in dev2

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#5]
za-dd-nids
Username: Adrian_Quintana
Pw: ???

**Comment by tokland** [comment]
Done. http://dev2.eyeseetea.com:8083/ admin / [samePass8082]

**Comment by adrianq** [comment]
Ok, working fine for me. I will keep this card opened until we set up the second server and do some testing with the two of them

**Comment by adrianq** [comment]
Servers set up here:
http://dev.eyeseetea.com:8082
http://dev2.eyeseetea.com:8083
