### ISSUE TITLE
Review metadata sync calls to create user roles

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#511]
If the user doesn't have access to the user roles, the app will try to create the roles and the server will throw a 500 exception. At least, we should have a try/catch otherwise the app won't even start

**Comment by SferaDev** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/commit/2d02ba32539a3a3306596abab272a65310abb36c

Didn't know there was a card for this
