### ISSUE TITLE
Add new pattern metadata selection for sync rules

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#545]
- [x] From branch feature/update-permissions-modules
- [x] New step 3 in metadata sync rule wizard: "Filter rules"
  - [x] Current metadata step won't be mandatory, however at least one of the metadata selection should happen (validate on step 3->4 transition)
  - [x] Object table showing available filters, one filter per row.
  - [x] Button to create new filter at the top-left corner. It opens a modal containing filter component
  - [x] Delete
  - [x] Edit
  - [x] Available filters:
    - [x] Created -> Absolute Date / Relative Date (Use Period - step 4 in aggregate). Substitute 'All periods' by 'all time'
    - [x] Last Updated -> Absolute Date / Relative Date (Use Period - step 4 in aggregate). Substitute 'All periods' by 'all time'
    - [x] Regex-like filter for name/code/*description -> Textfield with DHIS2 format (begins with, ends with, contains)
    - [x] Metadata Type -> Dropdown
    - [] Later:
    - [] Created by user or group -> Sharing Setting Component 
    - [] Last Updated by user or group -> Sharing Setting Component 
    - [] Sharing settings assigned to user or user group -> Sharing Setting Component
  - [] Later - Show results applying filter in the pop-up inside an object table

- [x] Summary: show filters (without results), keep specific metadata shown from step 2
- [x] Save filters to dataStore
- [x] Model: final metadata is metadata step 2 UNION result from step 3

**Comment by adrianq** [comment]
Tasks labelled as 'Later' are still missing
