### ISSUE TITLE
Identify changes between versions

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#555]
**Examples**

- Transformation code example: https://github.com/EyeSeeTea/metadata-synchronization/pull/564/commits/391003179f4f6d74f92766eacf37db15896388d0
- Test code example: https://github.com/EyeSeeTea/metadata-synchronization/pull/564/commits/1f9acd0f88e628e72cec159a40b4d25f3c9bf3df

**Check if backwards compatible without any changes**

- [x] 2.32: [Events] Added ``assignedUser`` property to an event
- [x] 2.32: [ProgramStage] Added ``enableUserAssignment``
- [x] 2.33: [Data element] Removed ``attributeValues.lastUpdated`` and `` attributeValues.created``

**Further investigation**

- [x] 2.31: [Chart and EventChart] Added ``yearlySeries``
- [x] 2.32: [DataSet] Added ``compulsoryDataElementOperands.aggregationType``
- [x] 2.32: [MapView] Added ``filterDimensions``
- [x] 2.33: [MapView] Added ``renderingStrategy``
- [x] 2.34: [MapView] Added ``digitGroupSeparator``
- [x] 2.34: [Dashboard] Changes on ``dashboardItems``, investigate what is contentCount and why it appears to be increased by 1 sometimes
- [x] 2.34: [Dashboard] Added prop visualization (investigate relationship with charts and eventReports and needed migration)
- [x] 2.34: [Chart and EventChart] Added ``digitGroupSeparator``
- [x] 2.34: [ProgramRuleAction] Added ``evaluationTime`` and ``evaluationEnvironments``
- [x] 2.35: [MapView] Added ``thematicMapType``

**Action required**

- [x] 2.31: [Program] Changed ``captureCoordinates`` boolean to string ``featureType`` (See Android SDK [docs](https://docs.dhis2.org/master/en/android-sdk/html/compatibility_strategy.html)) (false -> NONE. true -> POINT. POLYGON -> false), to keep compat we wouldn't remove strategy (investigate if backwards compatible)

- [x] 2.31: [ProgramStage] Changed ``validCompleteOnly`` boolean to string ``validationStrategy``, to keep compat we wouldn't remove strategy (investigate if backwards compatible)
Edited: Backwards compatible: Yes. For legacy reasons we must transform from 2.30 to 2.31 always as ON_COMPLETE, from 2.31 to 2.30 we can convert validationStrategy="ON_COMPLETE" to validCompleteOnly=true and alidationStrategy="ON_UPDATE_AND_INSERT" to validCompleteOnly=False. (https://docs.dhis2.org/2.31/en/user/html/dhis2_user_manual_en_full.html#create_event_program)
- [x] 2.32: [OrgUnit] Rename``featureType`` to ``geometry.type`` and ``coordinates`` to ``geometry.coordinates`` 
Edited: Backwards compatible: Yes
- [x] (@tokland) 2.31 to 2.30: [charts] Change "type" value "YEAR_OVER_YEAR_LINE" to "LINE" or "YEAR_OVER_YEAR_COLUMN" to "COLUMN". 
Change all yearlySerie in yearlySeries list to relativePeriods[period] as true. 
yearlySerie=THIS_YEAR to relativePeriods["thisYear"] = true
yearlySerie=LAST_YEAR to relativePeriods["lastYear"] = true
yearlySerie=LAST_5_YEARS to relativePeriods["last5Years"] = true
and set the others relative periods to false
And change the years in yearlySerie(any year is allowed) to periods:
`<yearlySeries><yearlySerie>2020</yearlySerie></yearlySeries> to: <periods><period id="2020"/></periods>
`
- [x] (@tokland) 2.34: [dashboardItems] Change "type" value "VISUALIZATION" to valid type f.e. "CHART"  (for charts and reportTables).

- [x] (@tokland) 2.34: [charts] Change "key" value "VISUALIZATION" to valid type f.e. "CHART",  series:"dx" -> columnDimensions:["dx],"seriesItems:[{series:id, axis:number}] -> optionalAxes[ {dimensionalItem:id, axis:1}],category: "pe", -> rowDimensions:["pe"]

- [x] (@tokland) 2.34: [reportTables] Change "type" value "VISUALIZATION" to "PIVOT_TABLE", rename: cumulative -> cumulativeValues, from yearlySeries to relativePeriods

- [x] (@tokland) 2.34: check dashboardItrems->maps/mapViews

**Comment by SferaDev** [comment]
### Differences found as per metadata

- Generic (Organisation Unit, DataSet, DataSet.compulsoryDataElementOperands, Indicator, Program, ProgramStage, ProgramStageSection, Dashboard, MapView, Constant, Option, CategoryOption, Catgegory, CategoryOptionCombo, EventChart, Chart, EventReport, ProgramIndicator, Map)

	- 2.32: Added ``displayFormName``
	
- Generic (Organisation Unit, DataSet, DataSet.compulsoryDataElementOperands, DataElement, Indicator, CategoryOption, CategoryOptionCombo, ProgramIndicator)
	
	- 2.35: Added ``periodOffset`` 

- Organisation Unit

	- 2.32: Removed ``featureType`` and ``coordinates``
	- 2.32: Added ``geometry.type`` and ``geometry.coordinates``
	
- DataSet

	- 2.32: Added ``compulsoryDataElementOperands.aggregationType``
	
- DataElement

	- 2.33: Removed ``attributeValues.lastUpdated`` and `` attributeValues.created``
	
- Indicator

	- 2.32: Added ``displayNumeratorDescription`` and ``displayDenominatorDescription``
	
- Program

	- 2.31: Removed ``captureCoordinates``
	- 2.31: Added ``featureType``
	
- ProgramStage

	- 2.31: Removed ``validCompleteOnly`` and added ``validationStrategy``
	- 2.32: Added ``enableUserAssignment``
	
- Dashboard

	- 2.34: Changes on ``dashboardItems``, contentCount increased by 1 and visualization added
	
- MapView

	- 2.32: Added ``filterDimensions``
	- 2.33: Added ``renderingStrategy``
	- 2.34: Added ``digitGroupSeparator``
	- 2.35: Added ``thematicMapType``
	
- User

	- 2.35: Added ``userCredentials.uuid``
	
- EventChart and Chart

	- 2.31: Added ``yearlySeries``
	- 2.34: Added ``digitGroupSeparator``
	
- ProgramRuleAction

	- 2.34: Added ``evaluationTime`` and ``evaluationEnvironments``
	
- Map

	- 2.32: Change ``mapView`` was a Ref and now it is bundled inside (does it matter on import?) -> Includes all changes of ``mapViews`` from 2.32 onwards

- Report

	- 2.34: Renamed ``reportTable`` into ``visualization``
	- 2.34: Renamed ``reportParams.paramGrandParentOrganisationUnit`` into ``reportParams.grandParentOrganisationUnit``
	- 2.34: Renamed ``reportParams.paramParentOrganisationUnit`` into ``reportParams.parentOrganisationUnit``
	- 2.34: Renamed ``reportParams.paramReportingPeriod`` into ``reportParams.reportingPeriod``
	- 2.34: Renamed ``reportParams.paramOrganisationUnit`` into ``reportParams.organisationUnit``

**Comment by idelcano** [comment]
2.31: Added yearlySeries [FURTHER INVESTIGATE] (Ina):
 Check if backwards compatible without any changes: Pending.
New feature
It is used in the data visualizer app
This is new feature is based on the selected periods and used in the new types of map YEAR_OVER_YEAR_LINE and YEAR_OVER_YEAR_COLUMN
Example of values:
```
<yearlySeries>
<yearlySerie>THIS_YEAR</yearlySerie>
<yearlySerie>LAST_YEAR</yearlySerie>
<yearlySerie>LAST_5_YEARS</yearlySerie>
<yearlySerie>2020</yearlySerie>
<yearlySerie>2019</yearlySerie>
<yearlySerie>2018</yearlySerie>
</yearlySeries>
```
You can add any year and the strings THIS_YEAR, LAST_YEAR, LAST_5_YEARS.

2.32: [DataSet] Added compulsoryDataElementOperands.aggregationType
 Check if backwards compatible without any changes:  YES
compulsoryDataElementOperands.aggregationType is the aggregationType of the dataelement



2.32: [MapView] Added filterDimensions
 Check if backwards compatible without any changes:  Pending
new app filter, allows you to filter by categories with the dataDimension value as true or by organizationunitgroupset containing orgunitgroups and orgunits to filter by org units

Migrated from db by:
```
-- Insert pe as filter for map views with fixed or relative periods in table "mapview_filters"
insert into mapview_filters (mapviewid, dimension, sort_order)
select mv.mapviewid as "mapviewid", 'pe' as "dimension", 0 as "sort_order"
from mapview mv 
where exists (
  select mapviewid 
  from mapview_periods
  where mapviewid = mv.mapviewid
  and periodid is not null)
or mv.relativeperiodsid is not null;
```
format:
```
<filterDimensions>
<filterDimension>pe</filterDimension>
<filterDimension>J5jldMd8OHv</filterDimension>
</filterDimensions>
```

 2.33: [MapView] Added renderingStrategy
 Check if backwards compatible without any changes:  Pending
new feature
Default: SINGLE
 Enum: SINGLE, SPLIT_BY_PERIOD, TIMELINE
This separates the render of the maps into several maps based on some periods (example: last five years in 5 years).

 2.34: [Chart and EventChart] Added digitGroupSeparator
 Check if backwards compatible without any changes:  Pending
new feature
It is selectable in pivot tables/event reports->options->Style->digit group separator
Options:
SPACE (default from system https://play.dhis2.org/2.32.6/api/systemSettings/keyAnalysisDigitGroupSeparator ) 
NONE
COMMA

 2.35: [MapView] Added thematicMapType
 Check if backwards compatible without any changes:  No tested
new feature
 Enum: CHOROPLETH, BUBBLE
 
I haven't found where to set that property.


 2.34: [Dashboard] Changes on dashboardItems, investigate what is contentCount and why it appears to be increased by 1 sometimes
 Check if backwards compatible without any changes: No tested (the new parent is visualization)
 it is calculated:
 https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-api/src/main/java/org/hisp/dhis/dashboard/DashboardItem.java#L265


 2.34: [Dashboard] Added prop visualization (investigate relationship with charts and eventReports and needed migration)
Check if backwards compatible without any changes: No tested
Migration file:  https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_13__Migrate_Data_Into_Visualization_Tables.sql

charts:
 series -> columnDimensions
 Series String
 columnDimensions List of strings
  
example:
from:
`"series": "dx"`
``` (this field contains the series dimensions assigned in the charts layout options.
to:
columnDimensions: [
"dx"
],
```
 "seriesItems":[]-> "optionalAxes": [],

 
 from.
```
     "seriesItems":[
	{
	    "series":"fbfJHSPpUQD",
	    "axis":1
	},
	{
	    "series":"cYeuwXTCPkU",
	    "axis":1
	}
    ],
```
To:
```
    "optionalAxes": [
        {
            "dimensionalItem": "fbfJHSPpUQD",
            "axis": 1
        },
        {
            "dimensionalItem": "cYeuwXTCPkU",
            "axis": 2
        }
    ]
``` 
 "category": "pe", -> "rowDimensions":["pe"]

new fields in visualization:
 "legendDisplayStyle": "FILL", not exists and not updated
  "hideEmptyColumns": false, not exists in chart, set as false in the migration
  "rowSubTotals": false, not exists in chart, set as false in the migration
  "showDimensionLabels": false, not exists in chart, set as false in the migration
  "fontSize": "NORMAL", fontSize not exists and not updated
  "showHierarchy": false,  not exists in chart, set as false in the migration
  "skipRounding": false,  not exists in chart, set as false in the migration
  "numberType": "VALUE",  not exists in chart, set as false in the migration
  "hideEmptyRows": false, not exists in chart, set as false in the migration
  "colTotals": false, not exists in chart, set as false in the migration
  "colSubTotals": false, not exists in chart, set as false in the migration
  "rowTotals": false,  not exists in chart, set as false in the migration
  "regression": false not exists in chart, set as false in the migration
  all not existing fields for charts was updated to false:
  UPDATE visualization SET regression = FALSE WHERE regression is NULL;
  
Added 
```
"data": {
      "read": false,
      "write": false
    },
```
in:
```
   "access": {
    "data": {
      "read": false,
      "write": false
    },
    "delete": false,
    "externalize": true,
    "manage": false,
    "read": true,
    "update": false,
    "write": false
  },
```



 report tables:
 new field:
  "type": "PIVOT_TABLE", It must be added in the report to visualization conversion.
rename:
  "cumulative": false, ->  "cumulativeValues": false,
new fields in visualization:
  "percentStackedValues": false,  not exists in report, set as false
  "noSpaceBetweenColumns": false, not exists in report, set as false
  "showData": false, not exists in report, set as false
  "regressionType": "NONE", not exists in report, not updated
https://docs.dhis2.org/2.32/javadoc/org/hisp/dhis/common/RegressionType.html
  "hideEmptyRowItems": "NONE", not exists in report, not updated
  https://docs.dhis2.org/master/javadoc/org/hisp/dhis/common/HideEmptyItemStrategy.html 
  "hideLegend": false, not exists in report, not updated

I found in the migration this validation:
```
 -- Set any possible empty or null NAME to an empty space ' '.
UPDATE reporttable SET name = ' ' WHERE COALESCE(name, '') = '' OR name IS NULL;
```

  "yearlySeries": []  already identified
  
  reportParams rename already identified

Other interesting links:
  https://github.com/dhis2/dhis2-core/pull/4432
  https://github.com/dhis2/data-visualizer-app/pull/541/files
https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml


 2.34: [ProgramRuleAction] Added evaluationTime and evaluationEnvironments
Check if backwards compatible without any changes: YES
evaluationEnvironments:
List of strings
values: "WEB", "ANDROID"
Default: ["WEB", "ANDROID"]
The migration update the old values to the default value.
I found no way to change it for now.

evaluationtime:
The migration update the old values to the default value.
 Default: Always, I found no way to change it for now.
Enum: ALWAYS, ON_COMPLETE, ON_DATA_ENTRY
