### ISSUE TITLE
Make import an async task and integrate with notifications

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#559]
Convert synchronization sync into an asynchronous process. Calls are sent to the DHIS2 server and executed in the background. The user received a message in the notification message box once the process finishes success or on failure. Notifications can be easily seen for the application landing page as a sort of bubble warning.

---------------

I've come to a point that I can replicate errors 504 Gateway time-out on the dockers constantly with a medium-sized payload.

We usually do not worry about this issue because WHO machines have the timeout largely increased in the tomcat configuration.

However we should at some point, I believe sooner than later, implement the import as an async task (it's just a flag on the POST call).

There're two possibilities I can think of (and we might integrate both of them):

- Polling, petition has been sent async but we keep the UI blocked until it has finished
- Real async, we forget about the import and create a notification that will be updated with the results

Note: This would resolve a similar issue that @idelcano has found too, when the requests are too large (like really big ones) user session hangs and returns failed because the connection has been closed. This is happening on WHO machines and the work-around he does is opening Event capture that does a polling to keep user session open.

**Comment by adrianq** [comment]
Moved to clickup
