### ISSUE TITLE
Refactors after release

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#572]
With @tokland we have discussed several refactors we would like to introduce, since we have a release right now it's not the best timing, but these can be safely introduced after the release.

- [ ] Infer return type of collections in ``storageRepository.getObjectInCollection`` with Namespace extension.
- [ ] Infer return type of repositories in ``repositoryFactory.get<GitHubRepositoryConstructor>``
- [x] Move helper "repository" builders from use cases to ``RepositoryFactory`` (with @cache decorator)
- [x] Rename ``common`` to ``react`` and move all components there, leaving ``webapp`` and ``widget`` with only pages/routing

**Comment by adrianq** [comment]
Let's talk tomorrow or whenever :)

**Comment by SferaDev** [comment]
> Let's talk tomorrow or whenever :)

Tomorrow looks good, already at home!

**Comment by SferaDev** [comment]
This is mainly done now, aside of the type inference which is not necessary right now after the move to the repository.
