### ISSUE TITLE
In package comparison, show objects in tooltip or dialog so the user can clearly see the differences

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#583]
- [ ] Show full contents of truncated strings in pop-up (with button [view more])

**Comment by tokland** [comment]
#602 took some time, I am moving this to Backlog for the moment, let's move when it to TODO again when necessary. Branch feature/package-diff-show-full-info-583 contains some code.

**Comment by adrianq** [comment]
Already in clickup
