### ISSUE TITLE
Change personal access token to GitHub Apps

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#658]
- [ ] Change the Store configuration page to add a "login with GitHub" button to update the credentials
- [ ] Add new router entry to handle callback from GitHub on authentication success and/or failure
- [ ] Update the dataStore to store the jwt (with a migration to invalidate existing credentials)
- [ ] Add a recurrent task that refreshes the existing jwt when expiry_date is soon
- [ ] Handle the expired jwt scenario that notifies the user that an administrator has to login again to GitHub
- [ ] Update the GitHubRepository to use the jwt instead of the token
- [ ] Review installation github app to see if it fits on scheduler or similar

**Comment by MiquelAdell** [comment]
moved to clickup https://app.clickup.com/t/8694j6k5x
