### ISSUE TITLE
Encoding issues with packages

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#671]
![image.png](https://app.gitkraken.com/api/glo/boards/5da04a8d796a7c000f8784e0/attachments/5f9bc5e46ddf520011306359)

**Comment by SferaDev** [comment]
```
let contentType = foo.headers.get("content-type");
// parse header encoding
let decoder = new TextDecoder(encoding);
let arrayBuffer = await foo.arrayBuffer();
let content = await decoder.decode(arrayBuffer);
let result = JSON.parse(content);
```

**Comment by adrianq** [comment]
This is not completely fixed. There is still a problem with the scheduler (see https://github.com/EyeSeeTea/d2-api/pull/68 comment). I have merged the original PR as it solved part of the problem and we can go ahead reviewing the other pending PRs
