### ISSUE TITLE
Create PR with .modules to WHO Play Store

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#672]
Repo: https://github.com/EyeSeeTea/DHIS2-standard-packages

**Comment by SferaDev** [comment]
Not sure against which repo should we do the PR, ours is behind WHO's.

For now created a staged commit on a fork of mine: https://github.com/WorldHealthOrganization/DHIS2-standard-packages/commit/31984b1f50853c530bfb67301ef5b66edc0bfcd8
