### ISSUE TITLE
Architecture Improvements

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/metadata-synchronization#677]
These improvements are related to code that I have modified or used in the package import wizard issue.

## Context

A good architecture hides implementation details. Implementation details are the concepts of relations with technology, libraries, frameworks, data sources, etc.. 

When detail implementations are not well hidden appears problems:
- Couple with libraries o detail implementations
- Duplicate code when there is data logic around the implementation detail
- You can’t write unit tests if use cases contain implementation details as dependencies 

When the use cases do not contain all necessary steps to realize the user actions appears problems:
- Duplicate code in the presentation views
- Unnecessary use cases creation
- You can’t write unit tests of a use case is not well identified in the domain and its steps are split between the presentation and domain

## Advice

When to define an architecture, a good point of view to keep in mind is that the use cases should be able to be executed from a terminal application or unit tests. This point of view focuses you to create the domain in the correct way.
For this reason, writing unit tests before writing the production code (TDD) helps to define good architecture.

## Architecture improvements found:

- [x] Uncouple store use cases from the datastore -> #694
- [ ] Uncouple package use cases from the datastore and github
    - Package uses cases (GetPackage, GetPackages) should be unique by domain entity, we should not have a different use case for every data source (instance or store). 
- [ ] StorageRepository should not be a repository. This couple the domain to the data source, the use cases should not know about data store namespaces. We should have repositories by important domain entities: (PackageRepository, StoreRepository, ModuleRepository, ImportedPackageRepository). With this approach we can reuse data logic and avoid potential bugs, for example, querying domain entities that contain a logic deletion in the data source as Store. 
- [ ] Code in the current StorageRepository should be a reuse code to invoke from all repositories that read and write in the data store but is not a repository because the storage domain concept does not exist, its a detail implementation.
- [ ] GitHubRepository should not be a repository. This couple the domain to GitHub data source, It's a detail implementation. The use cases should not know about GitHub data source, if we change from GitHub to GitLab or bitbucket the use case should not change it. We should have PackageRepository abstraction and then PackageD2Respoitory (read and write from the data store) and PackageGitHubRepository implementations. 
ListStorePackagesUseCase. A use case should not know how is stored the data (file names in Github, branches etc..)
- [ ] Use cases should not know about composition root, our composition root is a service locator pattern and only presentation views should know it. We are using composition root in the DiffPackageUseCase and CreatePackageUseCase to access to the sync use case to extract contents from an instance. Indirectly we are coupling use cases and a use case should not be coupled to others. Seems very similar work when we extract contents from module to package, maybe create a reuse process as a domain service used in different use cases?
**domain services**: Encapsulates business logic that doesn't naturally fit within a domain object (use case, entity). Doman services are processes used from several use cases and using several domain entities.
- [ ] DownloadRepository should not be a repository because the download concept is not a domain entity, the entity is Package, PackageRepository should be the abstraction invoked from DownloadPakckageUseCase, and PackageFileRepository for example should be the implementation.
- [ ] ValidateStoreUseCase receives a store entity, normally in the use cases is a best practice to receive identifiers and the use cases execute necessary invocations to the data source using repositories to retrieve the necessary data. This practice converts the use case more reusable, for example in the store list page to retrieve the store previously from presentation view would be not necessary. These cases are easily identifiable creating unit tests.
- [ ] Currently is not possible to create unit tests of use cases because It receives instance objects by the constructor, the current approach to decide repository (dhis2 by instance vs JSON) seems to be more data layer concern and not a domain concern.
- [ ] [new] - The coordination to import several packages and save the result, and save the imported package should be in the domain layer, maybe a new use case. These coordination steps to import several packages, save the result and save the imported package should be in the domain layer.
For example:  ImportPackagesUseCase.execute (packageIds:string[]), steps:
- Retrieve the current user
- For each package Id
   1 - retrieve package (store or instance) (using PackageRepository)
   2 - Import (using MetadataRepository)
   3 - Save Result (using ResultRepository)
   4 - Save ImportedPackage (using ImportedPackageRepository)
The coordination to import a package and save the result, and save the imported package should be in the domain layer, maybe reuse ImportPackagesUseCase passing one package id in the array parameter. 
Currently, this coordination logic is duplicated in the PackageImportDialog, when to import from the dialog and PackageListTable when to import a package from the contextual menu using several use cases (getPackage, GetStorePackage, SaveResult, SaveImportedPackage) but the use case should be a unique ImporPackagesUseCase and use cases for SaveResult and  Save Imported Package would be not necessary.
- [ ] Reuse the new Period Type in SyncRules and other places where we are validating fixed period with start and end dates
## Related articles to read about clean architecture
https://xurxodev.com/no-siempre-service-locator-es-un-anti-patron/
https://xurxodev.com/clean-architecture-code-smells-parte-1/
https://xurxodev.com/clean-architecture-code-smells-parte-2/

**Comment by adrianq** [comment]
Moved to a  Clickup issue
