### ISSUE TITLE
Implement instances configuration

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#7]
Done:

- [x] Add dependency to d2-ui-components
- [x] General Layout
- [x] Integrate listing table
- [x] Create new instance in global dataStore
- [x] Add Search textfield for filtering
- [x] Contextual options (Delete, Edit, Clone)
- [x] Change wizard to single page GUI
- [x] Change 'Endpoint' name to 'URL endpoint'
- [x] Implement delete
- [x] Implement tests with dev2 8083
- [x] Move description below server name.

Look and Feel:
- [x] Add spacing between Save and Cancel buttons
- [x] Save colour should be different
- [x] A bit more margin on the left side
- [x] Textfield should be full width
- [x] Fonts are slightly different than DHIS2, right? Can you have a look at it?

To-Do:
- [x] Add title and back button in all pages
- [x] Validation
   - [x] Pair URL-Username should be unique
   - [x] Check if connection is successful -> Show a different error for CORS and not found error (SEE COMMENT BELOW)
- [x] Confirm before delete with a dialog
- [x] Help button in instance-form-builder Heading, at the right of the title.
- [x] Create id by index for instances list
- [x] [Document](https://docs.google.com/document/d/1Z67aZGmoQF7tnmWSs-lpUwzglpqKQlT4wH7cwOMxx1I/edit) data store data model
- [ ] Implement [password encryption](https://www.npmjs.com/package/cryptr). Key should be read from a properties file - not hosted in github.

**Comment by adrianq** [comment]
Missing feature:
- [ ] Change wizard to single page GUI
- [ ] Add placeholder with an url example: https://play.dhis2.org/dev
- [ ] Change 'Endpoint' name to 'URL (endpoint)'
- [ ] Validation
   - [ ] URL-Name should be unique
   - [ ] Check connection is possible -> Show a different error for CORS and not found error
- [ ] Implement password encryption. Key should be read from a properties file - not hosted in github. See https://www.npmjs.com/package/cryptr
- [ ] Implement delete
- [ ] Implement tests with dev2 8083

**Comment by tokland** [comment]
Regarding "Check if connection is successful", some notes for the developer. Not the final code, just as a guide:

```
    public async check(): Promise<Response> {
        const { url, username, password } = this.data;
        const headers = new Headers({
            Authorization: "Basic " + Base64.encode(username + ":" + password),
        });
        try {
            const res = await fetch(url + "/api/system/info", { method: "GET", headers });
            console.log({ res });
            if (res.status == 401) {
                return { status: false, error: new Error("Wrong username/password") };
            } else if (!res.ok) {
                return { status: false, error: new Error(`Error: ${res.status}`) };
            } else {
                const json = await res.json();
                console.log({ json });

                if (json.version) {
                    return { status: true };
                } else {
                    return { status: false, error: new Error("Not a DHIS2 instance") };
                }
            }
        } catch (err) {
            console.log({ err });
            if (err.message && err.message.match(/Failed/)) {
                return {
                    status: false,
                    error: new Error(
                        `Network error (${
                            err.toString
                        }), probably wrong server host or CORS not enabled in DHIS2 instance`
                    ),
                };
            } else {
                return { status: false, error: err };
            }
        }
    }
```

Unfortunately, `fetch` (by design) does not pass info about network problems to the JS level. That means that there is no way to tell a wrong hostname (DNS failure) from problems with CORS. You see that info in the console, but this is opaque to the JS code. We can however see if there is an auth (401) problem. Let me know if there is problem, it's quite tricky.

**Comment by SferaDev** [comment]
@tokland I tend to use axios instead of fetch (mostly to ensure the code compatibility with both browser and node and because of the extensibility it provides as middleware).

I guess detecting the CORS issue with axios should be possible but I'm not 100% sure.

For OU sync I was using axios for now but we can change to a fetch implementation if you prefer (but we need to make sure it doesn't depend on the browser window as Phase 2 will be on a node environment)

**Comment by tokland** [comment]
Don't change it, it's ok to use axios. I'd be surprised if axios can tell what network error occurred, though, from what I've read, this info is sensitive and should not be passed to the JS level.
