### ISSUE TITLE
Review package comparison

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#701]
After installing a package, if we compare with local instance it shows differences

**Comment by xurxodev** [comment]
@adrianq Using the normal flow I have not reproduced. However, I have reproduced the bug following the next steps:
- I have created a new data element and data set (with the data element assigned) in the server 8085
- I have exported the data set using the advanced export app
- I have removed the dataset and data element in the server
- In the exported file, I have renamed data element uid and dataset uid in the id props and in the dataset elements props
- I have created a new package from the file and I have published to the store
- I have imported the package from the store 
- Comparing the imported package with the local instance, the process has found differences
![bug](https://user-images.githubusercontent.com/5593590/99065339-8bca7700-25a7-11eb-8e8c-4629989dde0b.png)
