### ISSUE TITLE
Create package manually only with supported metadata types

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#739]
When creating a package from a file we are currently adding all first-level ids to the package although from the app we only allow Dashboard, Program and Dataset to be part of package. Two options:
- Validate metadata types before creating the package
- Handle somehow this hidden metadata types when importing the package

See https://github.com/EyeSeeTea/metadata-synchronization/pull/733 for more information

**Comment by MiquelAdell** [comment]
moved to clickup https://app.clickup.com/t/8694j6bwp
