### ISSUE TITLE
Error creating dashboard json in 2.34.3 with new dashboard and visualizations

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/metadata-synchronization#798]
[json_files.zip](https://github.com/EyeSeeTea/metadata-synchronization/files/5724094/json_files.zip)

When I try to synchronize the rule it fails because there are null objects.
The dashboardItems listing is:
            "dashboardItems": [
                null,
                null,
                null,
                null,
...
Only some dashboard item of type text and two eventreports are right.

I attach 2 JSON files in the compressed file.
migration-eta-211220-dashboard-and-chart-metadata-sync-202012211219.json is the rule file when you download it by clicking on "download as JSON".

metadata_exported_with_dhis2_importexport.json is the file generated by import/export selecting the new dashboard. 
This one looks well-formed

**Comment by adrianq** [comment]
@idelcano is validating if this behaviour is still happening in 2.5.1

**Comment by idelcano** [comment]
Bad news @adrianq , It keeps happening in 2.5.1

MIGRATION - ETA - 211220 - Dashboard and Chart

**Comment by adrianq** [comment]
Moved to clickup
