### ISSUE TITLE
Implement OU Sync

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#8]
First Phase
- [x] General Layout: We will object table for now
- [x] Integrate filters: Text Search Filter
- [x] Sync Logic: 
   - Sync organisation units, organisation unit groups and organisation unit group sets and their attributes. If they don't exist we need to create it
   - Rules: If the parent OU does not exist on the slave we will not sync the OU. We will override any OU children.
   - importStrategy: CREATE_AND_UPDATE
   - mergeMode: MERGE or REPLACE
    - Exclusion rules for OU: users, userGroupAccesses, userAccesses, programs, 
dataSets, legendSets
    - Exclusion rules for OU Group: users, legendSets
    - Exclusion rules for OU Group Sets: dimensionalItemObject, users, legendSets

Second phase
- [x] Add a mechanism to come back to the home page and display the title of the page

**Comment by adrianq** [comment]
Some ideas from today meeting:

**How to model exclude and include rules**
excludeRules = [legendSet, users, userGroups, organisationUnitGroups.userGroups ...]
includeRules = [ attributes, organisationUnitGroups, organisationUnitGroups.attributes, organisationUnitGroups.organisationUnitGroupSets, organisationUnitGroups.organisationUnitGroupSets.attributes]

**Data structure to be stored in the data store, sync rules, etc**
dataStructure = {
	metadataType: '',
	ids: [],
	targetInstances: [],
	originInstance: id
}

**Comment by SferaDev** [comment]
**Data structure**
```js
export interface SynchronizationBuilder {
    targetInstances: string[];
    originInstance: string;
    metadata: {
        [metadataType: string]: string[];
    };
}

const builderExample: SynchronizationBuilder = {
    originInstance: "instanceId1",
    targetInstances: ["instanceId2"],
    metadata: [
        {
            metadataType1: ["myId1"],
            metadataType2: ["myId2"],
        }
    ]
};
```

**Configuration details**

importMode: COMMIT when importing, VALIDATE to check for errors
identifier: AUTO (will try for uid if not it will default to code)
importReportMode: FULL (will log debug and errors)
preheatMode: Seems to affect performance by preloading metadata before importing
importStrategy: CREATE_AND_UPDATE
atomicMode: Discuss
mergeMode: REPLACE

**Atomic Mode**

With default atomic (ALL) if a reference does not exists it will fail to import. Without atomic mode (NONE) if a reference does not exist it will properly import and the missing references will be erased on destination.

Previously to 2.30, import didn't have atomic and it tried to always import even with missing references.

**Invalid Parent**

If parent doesn't exists (invalid reference) it fails with ignored only on atomic mode. If atomic mode is disabled it will create the OU on level 1 without parent (BE CAREFUL).

**Deleted objects**

We do not detect deletions and we do not allow sync rules for deletions. (Potential Phase 3 improvement)

**Ideas from DHIS2 new import/export app**

![image](https://user-images.githubusercontent.com/2181866/54676643-66027b80-4b01-11e9-90b5-35d7210f6383.png)
![image](https://user-images.githubusercontent.com/2181866/54676967-386a0200-4b02-11e9-9d62-a8e3c13787f3.png)

**Example responses from metadata endpoint**

Invalid parent with atomic enabled:

```json
{
  "importParams": {
    "userOverrideMode": "NONE",
    "importMode": "VALIDATE",
    "identifier": "AUTO",
    "preheatMode": "REFERENCE",
    "importStrategy": "CREATE_AND_UPDATE",
    "atomicMode": "ALL",
    "mergeMode": "REPLACE",
    "flushMode": "AUTO",
    "skipSharing": false,
    "skipValidation": false,
    "username": "admin"
  },
  "status": "ERROR",
  "typeReports": [
    {
      "klass": "org.hisp.dhis.organisationunit.OrganisationUnit",
      "stats": {
        "created": 0,
        "updated": 0,
        "deleted": 0,
        "ignored": 2,
        "total": 2
      },
      "objectReports": [
        {
          "klass": "org.hisp.dhis.organisationunit.OrganisationUnit",
          "index": 0,
          "errorReports": [
            {
              "message": "Invalid reference [random, null] (OrganisationUnit) on object aa TEST 01 [zGv4gjlRmAX, TEST_02_UNIT] (OrganisationUnit) for association `parent`.",
              "mainKlass": "org.hisp.dhis.organisationunit.OrganisationUnit",
              "errorCode": "E5002"
            }
          ]
        }
      ]
    }
  ],
  "stats": {
    "created": 0,
    "updated": 0,
    "deleted": 0,
    "ignored": 2,
    "total": 2
  }
}
```

Invalid parent with atomic disabled:

```json
{
  "importParams": {
    "userOverrideMode": "NONE",
    "importMode": "VALIDATE",
    "identifier": "AUTO",
    "preheatMode": "REFERENCE",
    "importStrategy": "CREATE_AND_UPDATE",
    "atomicMode": "NONE",
    "mergeMode": "REPLACE",
    "flushMode": "AUTO",
    "skipSharing": false,
    "skipValidation": false,
    "username": "admin"
  },
  "status": "WARNING",
  "typeReports": [
    {
      "klass": "org.hisp.dhis.organisationunit.OrganisationUnit",
      "stats": {
        "created": 0,
        "updated": 1,
        "deleted": 0,
        "ignored": 0,
        "total": 1
      },
      "objectReports": [
        {
          "klass": "org.hisp.dhis.organisationunit.OrganisationUnit",
          "index": 0,
          "errorReports": [
            {
              "message": "Invalid reference [random, null] (OrganisationUnit) on object aa TEST 01 [zGv4gjlRmAX, TEST_02_UNIT] (OrganisationUnit) for association `parent`.",
              "mainKlass": "org.hisp.dhis.organisationunit.OrganisationUnit",
              "errorCode": "E5002"
            }
          ]
        }
      ]
    }
  ],
  "stats": {
    "created": 0,
    "updated": 1,
    "deleted": 0,
    "ignored": 0,
    "total": 1
  }
}
```

Valid OU:

```json
{
  "importParams": {
    "userOverrideMode": "NONE",
    "importMode": "VALIDATE",
    "identifier": "AUTO",
    "preheatMode": "REFERENCE",
    "importStrategy": "CREATE_AND_UPDATE",
    "atomicMode": "NONE",
    "mergeMode": "REPLACE",
    "flushMode": "AUTO",
    "skipSharing": false,
    "skipValidation": false,
    "username": "admin"
  },
  "status": "OK",
  "typeReports": [
    {
      "klass": "org.hisp.dhis.organisationunit.OrganisationUnit",
      "stats": {
        "created": 0,
        "updated": 1,
        "deleted": 0,
        "ignored": 0,
        "total": 1
      }
    }
  ],
  "stats": {
    "created": 0,
    "updated": 1,
    "deleted": 0,
    "ignored": 0,
    "total": 1
  }
}
```
