### ISSUE TITLE
Multipolygon geometry type changed to MultiPolygon.

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/metadata-synchronization#813]
In the migration from 2.34 to 2.34 of a multipolygon orgunit, the WHO server gives an error because it does not recognize the key.
The key should be: "MultiPolygon" instead of "Multipolygon"

Example:
https://extranet.who.int/dhis2-dev/api/organisationUnits/E7fpy26cxKT.json

**Comment by SferaDev** [comment]
Related: https://github.com/EyeSeeTea/metadata-synchronization/blob/development/src/data/transformations/PackageTransformations.ts#L18

**Comment by SferaDev** [comment]
Moved to clickup
