### ISSUE TITLE
Refine sync process performance

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#86]
Now:
- [x] Remove metadata package (https://github.com/EyeSeeTea/metadata-synchronization/pull/75)
- [x] Remove type report (raw data) and keep report field (https://github.com/EyeSeeTea/metadata-synchronization/pull/75)

- [x] Store data already retrieved (attributes, groups and groups sets and any other potential dependency) and don't ask for them again (give a try to coroutines, use a block scoped dictionary, if concurrency needs to be addressed wrap the promises with p-limit) 
- [x] Update message in loading screen (generator approach with a machine of states)

**Comment by SferaDev** [comment]
# Times

## First version

###1 Org Unit = 9 sec
![image](https://user-images.githubusercontent.com/6850223/58248871-39631e00-7d55-11e9-9533-d309a369cf02.png)

### 20 Org Unit = 180 sec
![image (1)](https://user-images.githubusercontent.com/6850223/58248872-39631e00-7d55-11e9-87da-7c686467861b.png)

### 40 Org Unit = 360 sec
![image (2)](https://user-images.githubusercontent.com/6850223/58248873-39fbb480-7d55-11e9-9ca7-e6cc5e93ec08.png)

## With id dictionary

### 1 Org Unit =

### 20 Org Unit =

### 40 Org Unit =

### 40k Org Unit =
