### ISSUE TITLE
i can't report issues with the feedback tool

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/metadata-synchronization#937]
Put: https://api.github.com/repos/EyeSeeTeaBotTest/snapshots/contents/screenshot-166815587590891213.png 404
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"
}

I was using brave navigator.
The app response is an error and my message was deleted, if i could try again i need start from zero to report the issue (but failed too again).

**Comment by idelcano** [comment]
(i tried it in preprod) https://portal-uat.who.int/dhis2/api/apps/MetaData-Synchronization/index.html#/sync/metadata
![screenshot-portal-uat who int-2022 11 11-09_42_32](https://user-images.githubusercontent.com/5302538/201301152-3e289a8f-56ca-4649-8d74-a0c2a6388406.png)

**Comment by MiquelAdell** [comment]
Done for next version
